name: HerokuContainer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x.x'
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build
        
      - name: Apply Migrations
        run: dotnet run --project ./Source/BlazorApp.DbMigrator -- "${{ secrets.POSTGRES_CONNECTION_STRING }}"
      
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
         files: './Source/BlazorApp.Host/appsettings.json'
        env:
         ConnectionStrings.DefaultConnection: ${{ secrets.POSTGRES_CONNECTION_STRING }}
         MailSettings.Host: ${{ secrets.EMAIL_HOST }}
         MailSettings.UserName: ${{ secrets.EMAIL_USERNAME }}
         MailSettings.Password: ${{ secrets.EMAIL_PASSWORD }}
    
      - name: Build and deploy the Docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ 'blazorapplication' }}
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
